plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mmohack.client'
    compileSdk 34

    defaultConfig {
        applicationId 'com.mmohack.client'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {}
